CREATE TABLE [prodcopy].[Account]
(
[accountcategorycode] [int] NULL,
[accountcategorycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountclassificationcode] [int] NULL,
[accountclassificationcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountid] [uniqueidentifier] NOT NULL,
[accountnumber] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountratingcode] [int] NULL,
[accountratingcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_addressid] [uniqueidentifier] NULL,
[address1_addresstypecode] [int] NULL,
[address1_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_freighttermscode] [int] NULL,
[address1_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_latitude] [float] NULL,
[address1_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_longitude] [float] NULL,
[address1_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_shippingmethodcode] [int] NULL,
[address1_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_utcoffset] [int] NULL,
[address2_addressid] [uniqueidentifier] NULL,
[address2_addresstypecode] [int] NULL,
[address2_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_freighttermscode] [int] NULL,
[address2_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_latitude] [float] NULL,
[address2_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_longitude] [float] NULL,
[address2_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_shippingmethodcode] [int] NULL,
[address2_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_utcoffset] [int] NULL,
[aging30] [money] NULL,
[aging30_base] [money] NULL,
[aging60] [money] NULL,
[aging60_base] [money] NULL,
[aging90] [money] NULL,
[aging90_base] [money] NULL,
[businesstypecode] [int] NULL,
[businesstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_accountscore] [int] NULL,
[cdi_allowtextmessages] [bit] NULL,
[cdi_allowtextmessagesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdby] [uniqueidentifier] NULL,
[createdbyexternalparty] [uniqueidentifier] NULL,
[createdbyexternalpartyname] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyexternalpartyyominame] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creditlimit] [money] NULL,
[creditlimit_base] [money] NULL,
[creditonhold] [bit] NULL,
[creditonholdname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customersizecode] [int] NULL,
[customersizecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customertypecode] [int] NULL,
[customertypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[defaultpricelevelid] [uniqueidentifier] NULL,
[defaultpricelevelidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkemail] [bit] NULL,
[donotbulkemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkpostalmail] [bit] NULL,
[donotbulkpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotemail] [bit] NULL,
[donotemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotfax] [bit] NULL,
[donotfaxname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotphone] [bit] NULL,
[donotphonename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotpostalmail] [bit] NULL,
[donotpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmarketingmaterialname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmm] [bit] NULL,
[emailaddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimage] [varbinary] (max) NULL,
[entityimage_timestamp] [bigint] NULL,
[entityimage_url] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimageid] [uniqueidentifier] NULL,
[exchangerate] [decimal] (28, 0) NULL,
[fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftpsiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[importsequencenumber] [int] NULL,
[industrycode] [int] NULL,
[industrycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isprivatename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastonholdtime] [datetime] NULL,
[lastusedincampaign] [datetime] NULL,
[marketcap] [money] NULL,
[marketcap_base] [money] NULL,
[masteraccountidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[masteraccountidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[masterid] [uniqueidentifier] NULL,
[merged] [bit] NULL,
[mergedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyexternalparty] [uniqueidentifier] NULL,
[modifiedbyexternalpartyname] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyexternalpartyyominame] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numberofemployees] [int] NULL,
[onholdtime] [int] NULL,
[opendeals] [int] NULL,
[opendeals_date] [datetime] NULL,
[opendeals_state] [int] NULL,
[openrevenue] [money] NULL,
[openrevenue_base] [money] NULL,
[openrevenue_date] [datetime] NULL,
[openrevenue_state] [int] NULL,
[originatingleadid] [uniqueidentifier] NULL,
[originatingleadidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[originatingleadidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[ownerid] [uniqueidentifier] NULL,
[owneridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ownershipcode] [int] NULL,
[ownershipcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owningbusinessunit] [uniqueidentifier] NULL,
[owningteam] [uniqueidentifier] NULL,
[owninguser] [uniqueidentifier] NULL,
[parentaccountid] [uniqueidentifier] NULL,
[parentaccountidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentaccountidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[participatesinworkflow] [bit] NULL,
[participatesinworkflowname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymenttermscode] [int] NULL,
[paymenttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pens01_subscription_penguinsenewsservice] [int] NULL,
[pens01_subscription_penguinsenewsservicename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pens01_subscription_penguinsgroupticketanncs] [int] NULL,
[pens01_subscription_penguinsgroupticketanncsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pens01_subscription_penguinslastminutetktdeals] [int] NULL,
[pens01_subscription_penguinslastminutetktdealsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pens01_subscription_penguinsvipticketalerts] [int] NULL,
[pens01_subscription_penguinsvipticketalertsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pens02_hospitalityownerid] [uniqueidentifier] NULL,
[pens02_hospitalityowneridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pens02_hospitalityowneridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_accounttype] [int] NULL,
[plus_accounttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_accttypedesc] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_corporateaccount] [uniqueidentifier] NULL,
[plus_corporateaccountname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_corporateaccountyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_deac] [bit] NULL,
[plus_deacname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_dncdaytimephone] [bit] NULL,
[plus_dncdaytimephonename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_dnceveningphone] [bit] NULL,
[plus_dnceveningphonename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_dncfax] [bit] NULL,
[plus_dncfaxname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_dncmobilephone] [bit] NULL,
[plus_dncmobilephonename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_lastassigned] [datetime] NULL,
[plus_lastpurchasem] [datetime] NULL,
[plus_lastviewedby] [uniqueidentifier] NULL,
[plus_lastviewedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_lastviewedbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_lastvieweddate] [datetime] NULL,
[plus_lifetimebroadcasts] [int] NULL,
[plus_lifetimeconcessionpurchases] [int] NULL,
[plus_lifetimegameattendance] [int] NULL,
[plus_lifetimemerchandisepurchases] [int] NULL,
[plus_lifetimepoints] [int] NULL,
[plus_lifetimesponsorpromos] [int] NULL,
[plus_loyaltreejoindate] [datetime] NULL,
[plus_primarycontact] [uniqueidentifier] NULL,
[plus_primarycontactname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_primarycontactyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_seaseonconcessionpurchases] [int] NULL,
[plus_seasonbroadcasts] [int] NULL,
[plus_seasongameattendance] [int] NULL,
[plus_seasonmerchandisepurchases] [int] NULL,
[plus_seasonpoints] [int] NULL,
[plus_seasonsponsorpromos] [int] NULL,
[plus_secondarycontact] [uniqueidentifier] NULL,
[plus_secondarycontactname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_secondarycontactyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_strid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_strowner] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_strpartnersalesperson] [uniqueidentifier] NULL,
[plus_strpartnersalespersonname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_strpartnersalespersonyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_strpartnerserviceperson] [uniqueidentifier] NULL,
[plus_strpartnerservicepersonname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_strpartnerservicepersonyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_system] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_systemid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmaccountid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmaccounttype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmacctrepname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmacctrepnum] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmaccttypedesc] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmactivepaymentplan] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmadddate2] [datetime] NULL,
[plus_tmadduser] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmbirthdate2] [datetime] NULL,
[plus_tmcompany] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmcompanyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmcountry] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmcustnameid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmdata] [bit] NULL,
[plus_tmdataname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmextsystem1id] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmextsystemid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmgender] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmgrooupcode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmindustry] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmmaritalstatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmnamefirst] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmnamelast] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmnamemi] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmnametitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmnametype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmoldacctid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo10] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo11] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo12] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo13] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo14] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo15] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo16] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo17] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo18] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo19] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo20] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo21] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo5] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo6] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo7] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo8] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmotherinfo9] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmpin] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmpoints] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmpointsid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmpointsitd] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmpointsytd] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmpreferredname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmprimarycode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmrecstatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmrelationshiptype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsalutation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsiccode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsicname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsincedate2] [datetime] NULL,
[plus_tmsolicitaddr] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsolicitemail] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsolicitphonecell] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsolicitphoneday] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsolicitphoneeve] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsolicitphonefax] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsourcedesc] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsourcelistname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmsourcename] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmticketusage] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmupdateuser] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmwaitinglistadddate] [datetime] NULL,
[plus_tmwaitinglistarea] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmwaitinglistplan] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_tmwaitlistnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_totalpurchasedm] [money] NULL,
[plus_totalpurchasedm_base] [money] NULL,
[plus_totalticketpurchasesm] [int] NULL,
[plus_waitinglistnum] [int] NULL,
[plus_waitinglistnumberofseats] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[plus_waitlistnumberofseats] [int] NULL,
[preferredappointmentdaycode] [int] NULL,
[preferredappointmentdaycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmenttimecode] [int] NULL,
[preferredappointmenttimecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredcontactmethodcode] [int] NULL,
[preferredcontactmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredequipmentid] [uniqueidentifier] NULL,
[preferredequipmentidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredserviceid] [uniqueidentifier] NULL,
[preferredserviceidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuserid] [uniqueidentifier] NULL,
[preferredsystemuseridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuseridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primarycontactid] [uniqueidentifier] NULL,
[primarycontactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primarycontactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primarysatoriid] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[primarytwitterid] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[processid] [uniqueidentifier] NULL,
[revenue] [money] NULL,
[revenue_base] [money] NULL,
[sharesoutstanding] [int] NULL,
[shippingmethodcode] [int] NULL,
[shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sic] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[slaid] [uniqueidentifier] NULL,
[slainvokedid] [uniqueidentifier] NULL,
[slainvokedidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[slaname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stageid] [uniqueidentifier] NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stockexchange] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[territorycode] [int] NULL,
[territorycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[territoryid] [uniqueidentifier] NULL,
[territoryidname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tickersymbol] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timezoneruleversionnumber] [int] NULL,
[transactioncurrencyid] [uniqueidentifier] NULL,
[transactioncurrencyidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[traversedpath] [nvarchar] (1250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[utcconversiontimezonecode] [int] NULL,
[versionnumber] [bigint] NULL,
[websiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[copyloaddate] [datetime] NULL CONSTRAINT [DF__Account__copyloa__440B1D61] DEFAULT (getdate())
)
GO
ALTER TABLE [prodcopy].[Account] ADD CONSTRAINT [PK__Account__F20699F61AA7B1BC] PRIMARY KEY CLUSTERED  ([accountid])
GO
